HEADERS = ["item", "category", "income", "expense"]
FINANCE_FILENAME = "my_finance_data.csv"
CATEGORIES_FILENAME = "categories.txt"
EXPORTED_FINANCE_FILENAME = "exported_finance_data.csv"
DATA_DIR = "data"
DATA_DIR_FINANCE_FILENAME = f"{DATA_DIR}/{FINANCE_FILENAME}"
DATA_DIR_CATEGORIES_FILENAME = f"{DATA_DIR}/{CATEGORIES_FILENAME}"
DATA_DIR_EXPORTED_FINANCE_FILENAME = f"{DATA_DIR}/{EXPORTED_FINANCE_FILENAME}"